Repository saladuit/minishell, pull requests merged in 2023-05, with the labels that each got.

#70 Executor♻️
  Makefile
  include/minishell.h
  makerc/common.mk
  makerc/config.mk
  src/builtins/cd.c
  src/builtins/echo.c
  src/builtins/env.c
  src/builtins/exit.c
  src/builtins/export.c
  src/builtins/pwd.c
  src/builtins/unset.c
  src/executor/execute_utils.c
  src/executor/executor.c
  src/minishell/minishell.c
  src/utils/message.c
  unit_test/src/env_cases.c
Labels: 🐛bug, 🔧refactor

#71 Here doc✨
  include/minishell.h
  src/executor/executor.c
  src/parser/heredoc.c
  unit_test/src/heredoc_cases.c
Labels: 💫enhancement, 🧪test

#78 Repair sheldon
  .gitignore
  include/minishell.h
  libs/libft/include/libft.h
  libs/libft/src/convert/ft_ltoi_with_overflow.c
  libs/libft/src/str/ft_str_count.c
  libs/libft/src/str/ft_strncmp.c
  src/builtins/builtin_cd.c
  src/builtins/builtin_echo.c
  src/builtins/builtin_exit.c
  src/builtins/builtin_export.c
  src/builtins/builtin_export_helpers.c
  src/builtins/builtin_export_validate.c
  src/env/env.c
  src/executor/execute_builtin.c
  src/executor/execute_child_command.c
  src/executor/execute_pipeline.c
  src/executor/executor.c
  src/executor/pipe.c
  src/expander/expand_dollar_node.c
  src/expander/expander.c
  src/lexer/lexer.c
  src/lexer/lexer_check.c
  src/minishell/minishell.c
  src/types/is_alnumunderscore.c
  src/types/is_equalssign.c
  src/types/is_whitespace.c
  src/utils/signal.c
  unit_test/include/unit_test.h
  unit_test/src/cd_cases.c
  unit_test/src/echo_cases.c
  unit_test/src/env_load_cases.c
  unit_test/src/exit_cases.c
  unit_test/src/expand_cases.c
  unit_test/src/export_cases.c
  unit_test/src/minishell_cases.c
Labels: 🐛bug, 💫enhancement, 🧪test

#79 Repair sheldon sala
  Makefile
  unit_test/src/env_cases.c
  unit_test/src/exit_cases.c
  unit_test/src/export_cases.c
Labels: 🐛bug

#82 Final fix down
  Makefile
  include/minishell.h
  makerc/common.mk
  makerc/config.mk
  src/builtins/cd.c
  src/builtins/echo.c
  src/builtins/env.c
  src/builtins/exit.c
  src/builtins/export.c
  src/builtins/export_helpers.c
  src/builtins/pwd.c
  src/builtins/unset.c
  src/executor/execute_builtin.c
  src/executor/execute_child_command.c
  src/executor/execute_pipeline.c
  src/executor/executor.c
  src/executor/open.c
  src/executor/redirect.c
  src/expander/expander.c
  src/expander/expander_handle_edge_cases.c
  src/lexer/lexer.c
  src/minishell/minishell.c
  src/parser/argument.c
  src/parser/ast.c
  src/parser/command.c
  src/parser/command_table.c
  src/parser/heredoc.c
  src/parser/redir.c
  src/parser/redir_helpers.c
  unit_test/src/echo_cases.c
  unit_test/src/expand_cases.c
  unit_test/src/lexer_cases.c
  unit_test/src/minishell_cases.c
Labels: 🐛bug, 💫enhancement
